### ISSUE TITLE
在微信小程序中使用报错

### ISSUE THREAD

**Issue by ZhangShuangV** [ElemeFE/v-charts#369]
### Summary 简述
```
thirdScriptError
this.dom.getContext is not a function;at pages/demo/main page lifeCycleMethod onReady function
TypeError: this.dom.getContext is not a function
    at Layer.initContext (http://127.0.0.1:59458/appservice/static/js/vendor.js:35447:25)
    at new Painter (http://127.0.0.1:59458/appservice/static/js/vendor.js:34497:15)
    at new ZRender (http://127.0.0.1:59458/appservice/static/js/vendor.js:21698:17)
    at Object.init (http://127.0.0.1:59458/appservice/static/js/vendor.js:21612:12)
    at new ECharts (http://127.0.0.1:59458/appservice/static/js/vendor.js:3392:31)
    at Object.init (http://127.0.0.1:59458/appservice/static/js/vendor.js:4864:15)
    at VueComponent.init (http://127.0.0.1:59458/appservice/static/js/vendor.js:62529:40)
    at VueComponent.boundFn [as init] (http://127.0.0.1:59458/appservice/static/js/vendor.js:7624:12)
    at VueComponent.mounted (http://127.0.0.1:59458/appservice/static/js/vendor.js:62603:12)
    at callHook (http://127.0.0.1:59458/appservice/static/js/vendor.js:9718:21)
```

**Comment by xiguaxigua** [comment]
当前版本没有做微信小程序的兼容

**Comment by zaxlct** [comment]
希望支持小程序（Mpvue）

**Comment by dutianyu** [comment]
希望支持小程序/uni-app
