### ISSUE TITLE
热力图  rows 字段 为空数组时报错

### ISSUE THREAD

**Issue by tgxpuisb** [ElemeFE/v-charts#423]
### Summary 简述

热力图  rows 字段 为空数组时报错
Uncaught (in promise) DOMException: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('undefined') could not be parsed as a color.
    at Style.getGradient (webpack-internal:///./node_modules/zrender/lib/graphic/Style.js:435:22)
    at Sub.brush (webpack-internal:///./node_modules/zrender/lib/graphic/Path.js:55:36)
    at Painter._doPaintEl (webpack-internal:///./node_modules/zrender/lib/Painter.js:502:10)
    at Painter._doPaintList (webpack-internal:///./node_modules/zrender/lib/Painter.js:431:14)
    at Painter._paintList (webpack-internal:///./node_modules/zrender/lib/Painter.js:364:25)
    at Painter.refresh (webpack-internal:///./node_modules/zrender/lib/Painter.js:251:10)
    at ZRender.refreshImmediately (webpack-internal:///./node_modules/zrender/lib/zrender.js:237:18)
    at ZRender.flush (webpack-internal:///./node_modules/zrender/lib/zrender.js:264:12)
    at ECharts.echartsProto.setOption (webpack-internal:///./node_modules/echarts/lib/echarts.js:375:14)
    at VueComponent.optionsHandler (webpack-internal:///./node_modules/v-charts/lib/index.js:1237:22)
getGradient @ Style.js?77c4:435
brush @ Path.js?1b15:55
_doPaintEl @ Painter.js?2345:502
_doPaintList @ Painter.js?2345:431
_paintList @ Painter.js?2345:364
refresh @ Painter.js?2345:251
refreshImmediately @ zrender.js?86fd:237
flush @ zrender.js?86fd:264
echartsProto.setOption @ echarts.js?21c7:375
optionsHandler @ index.js?bcee:1237
Promise.then (async)
dataHandler @ index.js?bcee:1155
(anonymous) @ index.js?bcee:331
setTimeout (async)
(anonymous) @ index.js?bcee:330
init @ index.js?bcee:1281
mounted @ index.js?bcee:1357
callHook @ vue.esm.js?efeb:2921
insert @ vue.esm.js?efeb:4158
invokeInsertHook @ vue.esm.js?efeb:5960
patch @ vue.esm.js?efeb:6179
Vue._update @ vue.esm.js?efeb:2660
updateComponent @ vue.esm.js?efeb:2788
get @ vue.esm.js?efeb:3142
Watcher @ vue.esm.js?efeb:3131
mountComponent @ vue.esm.js?efeb:2795
Vue.$mount @ vue.esm.js?efeb:8540
Vue.$mount @ vue.esm.js?efeb:10939
Vue._init @ vue.esm.js?efeb:4640
Vue @ vue.esm.js?efeb:4729
(anonymous) @ main.js?1c90:16
./src/main.js @ app.js:5120
__webpack_require__ @ app.js:679
fn @ app.js:89
0 @ app.js:5153
__webpack_require__ @ app.js:679
(anonymous) @ app.js:725
(anonymous) @ app.js:728
backend.js:1  vue-devtools  Detected Vue v2.5.16 
Style.js?77c4:435 Uncaught DOMException: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('undefined') could not be parsed as a color.
    at Style.getGradient (webpack-internal:///./node_modules/zrender/lib/graphic/Style.js:435:22)
    at Sub.brush (webpack-internal:///./node_modules/zrender/lib/graphic/Path.js:55:36)
    at Painter._doPaintEl (webpack-internal:///./node_modules/zrender/lib/Painter.js:502:10)
    at Painter._doPaintList (webpack-internal:///./node_modules/zrender/lib/Painter.js:431:14)
    at Painter._paintList (webpack-internal:///./node_modules/zrender/lib/Painter.js:364:25)
    at Painter.refresh (webpack-internal:///./node_modules/zrender/lib/Painter.js:251:10)
    at ZRender.refreshImmediately (webpack-internal:///./node_modules/zrender/lib/zrender.js:237:18)
    at ZRender.flush (webpack-internal:///./node_modules/zrender/lib/zrender.js:264:12)
    at Object.eval [as update] (webpack-internal:///./node_modules/zrender/lib/core/util.js:424:17)
    at Animation._update (webpack-internal:///./node_modules/zrender/lib/animation/Animation.js:159:18)

### Expect 期望结果

控制台不报错

### Reproduce 重现示例
<template>
  <ve-heatmap :data="chartData" :settings="chartSettings"></ve-heatmap>
</template>

<script>
  export default {
    data () {
      this.chartSettings = {
        position: 'china',
        type: 'map',
        geo: {
          label: {
            emphasis: {
              show: false
            }
          },
          itemStyle: {
            normal: {
              areaColor: '#323c48',
              borderColor: '#111'
            },
            emphasis: {
              areaColor: '#2a333d'
            }
          }
        }
      }
      return {
        chartData: {
          columns: ['lat', 'lng', '人数'],
          rows: [
            // { 'lat': 115.892151, 'lng': 28.676493, '人数': 1000 }
          ]
        }
      }
    }
  }
</script>

**Comment by xiguaxigua** [comment]
似乎是 echarts 本身的问题 https://jsfiddle.net/aj9cemsf/40/
可以预先设置一个坐标不会体现在图上的数据作为默认值来解决这个问题

**Comment by xiguaxigua** [comment]
更新版本试试 （v1.17.7）
