### ISSUE TITLE
构建时提示路径解析错误

### ISSUE THREAD

**Issue by li-zhixin** [ElemeFE/v-charts#706]
### Summary 简述

运行如下指令构建项目时,提示路径错误

```bash
npm run build
```

> 报错如下:

```bash
(node:2656) UnhandledPromiseRejectionWarning: Error: Could not resolve '../../core' from src\packages\bar\index.js
    at error (C:\Users\liuzh\WebstormProjects\v-charts\node_modules\rollup\dist\rollup.js:3337:15)
    at C:\Users\liuzh\WebstormProjects\v-charts\node_modules\rollup\dist\rollup.js:21005:25
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
(node:2656) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (reje
ction id: 1)
```
### Expect 期望结果

正常打包构建

### Reproduce 重现示例

```bash
npm install
npm run build
```
>  运行环境:
>  终端: gitbash
>  系统: windows10 
>  node: 8.12.0
>  npm: 6.4.1
>  IDE: webstorm

**Comment by Himangguo** [comment]
请问怎么解决的？
