### ISSUE TITLE
打包时找不到‘core’文件

### ISSUE THREAD

**Issue by 1652866741** [ElemeFE/v-charts#765]
### Summary 简述
执行npm run build命令时，报‘../../core’文件找不到

**Comment by 1652866741** [comment]
(node:6024) UnhandledPromiseRejectionWarning: Error: Could not resolve '../../co
re' from src\packages\heatmap\index.js
    at error (D:\v-charts-fix-watch-prop-asset\node_modules\rollup\dist\rollup.j
s:3337:15)
    at D:\v-charts-fix-watch-prop-asset\node_modules\rollup\dist\rollup.js:21005
:25
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
(node:6024) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 34)
(node:6024) UnhandledPromiseRejectionWarning: Error: Could not resolve '../../co
re' from src\packages\scatter\index.js
    at error (D:\v-charts-fix-watch-prop-asset\node_modules\rollup\dist\rollup.j
s:3337:15)
    at D:\v-charts-fix-watch-prop-asset\node_modules\rollup\dist\rollup.js:21005
:25
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
(node:6024) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 35)

**Comment by dewfall123** [comment]
请问怎么解决的？

**Comment by Himangguo** [comment]
请问怎么解决的？
